version: '3'
services:
  web:
    build: 
      # Contrary to the other docker-compose, 
      # we can't specify the dir because we don't have 
      # a Dockerfile but instead Dockerfile.dev
      # To fix the issue, we add to params: context and ...
      context: . # This specifies where the files and folders will be pulled from
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"] # This line overwrites the default command